/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Asset = IDL.Variant({
  'eurUsdOtc' : IDL.Null,
  'usdJpyOtc' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'preferredAsset' : IDL.Opt(Asset),
});
export const Signal = IDL.Variant({
  'put' : IDL.Null,
  'call' : IDL.Null,
  'noTrade' : IDL.Null,
});
export const Strategy = IDL.Variant({
  'colorFollowsColor' : IDL.Null,
  'combined' : IDL.Null,
  'trapWicks' : IDL.Null,
});
export const Outcome = IDL.Variant({
  'win' : IDL.Null,
  'loss' : IDL.Null,
  'notTaken' : IDL.Null,
  'unknown' : IDL.Null,
});
export const TradeAnalysis = IDL.Record({
  'id' : IDL.Text,
  'secondContinuation' : IDL.Opt(
    IDL.Record({
      'closeInCurrentMinute' : IDL.Bool,
      'continuationAfterLoss' : IDL.Bool,
    })
  ),
  'totalBearishCandles' : IDL.Nat,
  'endingMomentumPercentage' : IDL.Float64,
  'momentumActivePercentage' : IDL.Float64,
  'asset' : Asset,
  'totalHammerCandles' : IDL.Nat,
  'userCorrectedSignal' : IDL.Opt(Signal),
  'generatedSignal' : Signal,
  'confidenceScoreAfterCorrection' : IDL.Float64,
  'owner' : IDL.Principal,
  'totalBullishCandles' : IDL.Nat,
  'trapWickActive' : IDL.Bool,
  'trapWicksTriggered' : IDL.Bool,
  'strategy' : Strategy,
  'highMomentumPercentage' : IDL.Float64,
  'strongMomentumPattern' : IDL.Bool,
  'finalWickAttempt' : IDL.Bool,
  'failedWickAttempts' : IDL.Nat,
  'trendStartPercentage' : IDL.Float64,
  'totalBeltCandles' : IDL.Nat,
  'isContinuationTrade' : IDL.Bool,
  'reversalPercentage' : IDL.Float64,
  'createdTimestamp' : Time,
  'weakMomentumPercenage' : IDL.Float64,
  'indicators' : IDL.Record({
    'adx' : IDL.Float64,
    'hma' : IDL.Float64,
    'rsi' : IDL.Float64,
    'emaFast' : IDL.Float64,
    'emaSlow' : IDL.Float64,
    'stochasticFast' : IDL.Float64,
    'stochasticSlow' : IDL.Float64,
    'macd' : IDL.Float64,
    'currentCandleFullWickRatio' : IDL.Float64,
    'candleCountCurrentTrend' : IDL.Nat,
    'momentum' : IDL.Float64,
    'currentCandleMaxBodyWickRatio' : IDL.Float64,
    'dmiDirectional' : IDL.Float64,
    'currentCandleFullBodyWickRatio' : IDL.Float64,
  }),
  'trapStrongReversalPattern' : IDL.Bool,
  'closedTimestamp' : IDL.Opt(Time),
  'trapDojiCandle' : IDL.Bool,
  'confidence' : IDL.Float64,
  'firstContinuation' : IDL.Opt(
    IDL.Record({
      'closeInCurrentMinute' : IDL.Bool,
      'continuationAfterLoss' : IDL.Bool,
    })
  ),
  'outcome' : IDL.Opt(Outcome),
  'trapResistanceReversalPercentage' : IDL.Float64,
  'totalDojiCandles' : IDL.Nat,
  'totalInvertedHammerCandles' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'analysisIdExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'anyAnalysisAssetIsEurUsdOtc' : IDL.Func([], [IDL.Bool], ['query']),
  'anyTradeAnalysisCreatedBefore' : IDL.Func([Time], [IDL.Bool], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTradeAnalysis' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNumAnalyses' : IDL.Func([], [IDL.Nat], ['query']),
  'getTradeAnalyses' : IDL.Func([], [IDL.Vec(TradeAnalysis)], ['query']),
  'getTradeAnalysesByOutcome' : IDL.Func(
      [IDL.Opt(Outcome)],
      [IDL.Vec(TradeAnalysis)],
      ['query'],
    ),
  'getTradeAnalysesSortedByTime' : IDL.Func(
      [],
      [IDL.Vec(TradeAnalysis)],
      ['query'],
    ),
  'getTradeAnalysis' : IDL.Func([IDL.Text], [TradeAnalysis], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasAnalysisWithOutcome' : IDL.Func([Outcome], [IDL.Bool], ['query']),
  'hasTradeAnalysisWithConfidence' : IDL.Func(
      [IDL.Float64],
      [IDL.Bool],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'storeTradeAnalysis' : IDL.Func(
      [
        IDL.Text,
        Asset,
        Strategy,
        Signal,
        IDL.Float64,
        Time,
        IDL.Opt(Time),
        IDL.Opt(Outcome),
        IDL.Opt(Signal),
        IDL.Float64,
        IDL.Record({
          'adx' : IDL.Float64,
          'hma' : IDL.Float64,
          'rsi' : IDL.Float64,
          'emaFast' : IDL.Float64,
          'emaSlow' : IDL.Float64,
          'stochasticFast' : IDL.Float64,
          'stochasticSlow' : IDL.Float64,
          'macd' : IDL.Float64,
          'currentCandleFullWickRatio' : IDL.Float64,
          'candleCountCurrentTrend' : IDL.Nat,
          'momentum' : IDL.Float64,
          'currentCandleMaxBodyWickRatio' : IDL.Float64,
          'dmiDirectional' : IDL.Float64,
          'currentCandleFullBodyWickRatio' : IDL.Float64,
        }),
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Bool,
        IDL.Bool,
        IDL.Nat,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(
          IDL.Record({
            'closeInCurrentMinute' : IDL.Bool,
            'continuationAfterLoss' : IDL.Bool,
          })
        ),
        IDL.Opt(
          IDL.Record({
            'closeInCurrentMinute' : IDL.Bool,
            'continuationAfterLoss' : IDL.Bool,
          })
        ),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Asset = IDL.Variant({ 'eurUsdOtc' : IDL.Null, 'usdJpyOtc' : IDL.Null });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'preferredAsset' : IDL.Opt(Asset),
  });
  const Signal = IDL.Variant({
    'put' : IDL.Null,
    'call' : IDL.Null,
    'noTrade' : IDL.Null,
  });
  const Strategy = IDL.Variant({
    'colorFollowsColor' : IDL.Null,
    'combined' : IDL.Null,
    'trapWicks' : IDL.Null,
  });
  const Outcome = IDL.Variant({
    'win' : IDL.Null,
    'loss' : IDL.Null,
    'notTaken' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const TradeAnalysis = IDL.Record({
    'id' : IDL.Text,
    'secondContinuation' : IDL.Opt(
      IDL.Record({
        'closeInCurrentMinute' : IDL.Bool,
        'continuationAfterLoss' : IDL.Bool,
      })
    ),
    'totalBearishCandles' : IDL.Nat,
    'endingMomentumPercentage' : IDL.Float64,
    'momentumActivePercentage' : IDL.Float64,
    'asset' : Asset,
    'totalHammerCandles' : IDL.Nat,
    'userCorrectedSignal' : IDL.Opt(Signal),
    'generatedSignal' : Signal,
    'confidenceScoreAfterCorrection' : IDL.Float64,
    'owner' : IDL.Principal,
    'totalBullishCandles' : IDL.Nat,
    'trapWickActive' : IDL.Bool,
    'trapWicksTriggered' : IDL.Bool,
    'strategy' : Strategy,
    'highMomentumPercentage' : IDL.Float64,
    'strongMomentumPattern' : IDL.Bool,
    'finalWickAttempt' : IDL.Bool,
    'failedWickAttempts' : IDL.Nat,
    'trendStartPercentage' : IDL.Float64,
    'totalBeltCandles' : IDL.Nat,
    'isContinuationTrade' : IDL.Bool,
    'reversalPercentage' : IDL.Float64,
    'createdTimestamp' : Time,
    'weakMomentumPercenage' : IDL.Float64,
    'indicators' : IDL.Record({
      'adx' : IDL.Float64,
      'hma' : IDL.Float64,
      'rsi' : IDL.Float64,
      'emaFast' : IDL.Float64,
      'emaSlow' : IDL.Float64,
      'stochasticFast' : IDL.Float64,
      'stochasticSlow' : IDL.Float64,
      'macd' : IDL.Float64,
      'currentCandleFullWickRatio' : IDL.Float64,
      'candleCountCurrentTrend' : IDL.Nat,
      'momentum' : IDL.Float64,
      'currentCandleMaxBodyWickRatio' : IDL.Float64,
      'dmiDirectional' : IDL.Float64,
      'currentCandleFullBodyWickRatio' : IDL.Float64,
    }),
    'trapStrongReversalPattern' : IDL.Bool,
    'closedTimestamp' : IDL.Opt(Time),
    'trapDojiCandle' : IDL.Bool,
    'confidence' : IDL.Float64,
    'firstContinuation' : IDL.Opt(
      IDL.Record({
        'closeInCurrentMinute' : IDL.Bool,
        'continuationAfterLoss' : IDL.Bool,
      })
    ),
    'outcome' : IDL.Opt(Outcome),
    'trapResistanceReversalPercentage' : IDL.Float64,
    'totalDojiCandles' : IDL.Nat,
    'totalInvertedHammerCandles' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'analysisIdExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'anyAnalysisAssetIsEurUsdOtc' : IDL.Func([], [IDL.Bool], ['query']),
    'anyTradeAnalysisCreatedBefore' : IDL.Func([Time], [IDL.Bool], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTradeAnalysis' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNumAnalyses' : IDL.Func([], [IDL.Nat], ['query']),
    'getTradeAnalyses' : IDL.Func([], [IDL.Vec(TradeAnalysis)], ['query']),
    'getTradeAnalysesByOutcome' : IDL.Func(
        [IDL.Opt(Outcome)],
        [IDL.Vec(TradeAnalysis)],
        ['query'],
      ),
    'getTradeAnalysesSortedByTime' : IDL.Func(
        [],
        [IDL.Vec(TradeAnalysis)],
        ['query'],
      ),
    'getTradeAnalysis' : IDL.Func([IDL.Text], [TradeAnalysis], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasAnalysisWithOutcome' : IDL.Func([Outcome], [IDL.Bool], ['query']),
    'hasTradeAnalysisWithConfidence' : IDL.Func(
        [IDL.Float64],
        [IDL.Bool],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'storeTradeAnalysis' : IDL.Func(
        [
          IDL.Text,
          Asset,
          Strategy,
          Signal,
          IDL.Float64,
          Time,
          IDL.Opt(Time),
          IDL.Opt(Outcome),
          IDL.Opt(Signal),
          IDL.Float64,
          IDL.Record({
            'adx' : IDL.Float64,
            'hma' : IDL.Float64,
            'rsi' : IDL.Float64,
            'emaFast' : IDL.Float64,
            'emaSlow' : IDL.Float64,
            'stochasticFast' : IDL.Float64,
            'stochasticSlow' : IDL.Float64,
            'macd' : IDL.Float64,
            'currentCandleFullWickRatio' : IDL.Float64,
            'candleCountCurrentTrend' : IDL.Nat,
            'momentum' : IDL.Float64,
            'currentCandleMaxBodyWickRatio' : IDL.Float64,
            'dmiDirectional' : IDL.Float64,
            'currentCandleFullBodyWickRatio' : IDL.Float64,
          }),
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Bool,
          IDL.Bool,
          IDL.Nat,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(
            IDL.Record({
              'closeInCurrentMinute' : IDL.Bool,
              'continuationAfterLoss' : IDL.Bool,
            })
          ),
          IDL.Opt(
            IDL.Record({
              'closeInCurrentMinute' : IDL.Bool,
              'continuationAfterLoss' : IDL.Bool,
            })
          ),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };