/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Asset = { 'eurUsdOtc' : null } |
  { 'usdJpyOtc' : null };
export type Outcome = { 'win' : null } |
  { 'loss' : null } |
  { 'notTaken' : null } |
  { 'unknown' : null };
export type Signal = { 'put' : null } |
  { 'call' : null } |
  { 'noTrade' : null };
export type Strategy = { 'colorFollowsColor' : null } |
  { 'combined' : null } |
  { 'trapWicks' : null };
export type Time = bigint;
export interface TradeAnalysis {
  'id' : string,
  'secondContinuation' : [] | [
    { 'closeInCurrentMinute' : boolean, 'continuationAfterLoss' : boolean }
  ],
  'totalBearishCandles' : bigint,
  'endingMomentumPercentage' : number,
  'momentumActivePercentage' : number,
  'asset' : Asset,
  'totalHammerCandles' : bigint,
  'userCorrectedSignal' : [] | [Signal],
  'generatedSignal' : Signal,
  'confidenceScoreAfterCorrection' : number,
  'owner' : Principal,
  'totalBullishCandles' : bigint,
  'trapWickActive' : boolean,
  'trapWicksTriggered' : boolean,
  'strategy' : Strategy,
  'highMomentumPercentage' : number,
  'strongMomentumPattern' : boolean,
  'finalWickAttempt' : boolean,
  'failedWickAttempts' : bigint,
  'trendStartPercentage' : number,
  'totalBeltCandles' : bigint,
  'isContinuationTrade' : boolean,
  'reversalPercentage' : number,
  'createdTimestamp' : Time,
  'weakMomentumPercenage' : number,
  'indicators' : {
    'adx' : number,
    'hma' : number,
    'rsi' : number,
    'emaFast' : number,
    'emaSlow' : number,
    'stochasticFast' : number,
    'stochasticSlow' : number,
    'macd' : number,
    'currentCandleFullWickRatio' : number,
    'candleCountCurrentTrend' : bigint,
    'momentum' : number,
    'currentCandleMaxBodyWickRatio' : number,
    'dmiDirectional' : number,
    'currentCandleFullBodyWickRatio' : number,
  },
  'trapStrongReversalPattern' : boolean,
  'closedTimestamp' : [] | [Time],
  'trapDojiCandle' : boolean,
  'confidence' : number,
  'firstContinuation' : [] | [
    { 'closeInCurrentMinute' : boolean, 'continuationAfterLoss' : boolean }
  ],
  'outcome' : [] | [Outcome],
  'trapResistanceReversalPercentage' : number,
  'totalDojiCandles' : bigint,
  'totalInvertedHammerCandles' : bigint,
}
export interface UserProfile {
  'name' : string,
  'preferredAsset' : [] | [Asset],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'analysisIdExists' : ActorMethod<[string], boolean>,
  'anyAnalysisAssetIsEurUsdOtc' : ActorMethod<[], boolean>,
  'anyTradeAnalysisCreatedBefore' : ActorMethod<[Time], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteTradeAnalysis' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNumAnalyses' : ActorMethod<[], bigint>,
  'getTradeAnalyses' : ActorMethod<[], Array<TradeAnalysis>>,
  'getTradeAnalysesByOutcome' : ActorMethod<
    [[] | [Outcome]],
    Array<TradeAnalysis>
  >,
  'getTradeAnalysesSortedByTime' : ActorMethod<[], Array<TradeAnalysis>>,
  'getTradeAnalysis' : ActorMethod<[string], TradeAnalysis>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasAnalysisWithOutcome' : ActorMethod<[Outcome], boolean>,
  'hasTradeAnalysisWithConfidence' : ActorMethod<[number], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'storeTradeAnalysis' : ActorMethod<
    [
      string,
      Asset,
      Strategy,
      Signal,
      number,
      Time,
      [] | [Time],
      [] | [Outcome],
      [] | [Signal],
      number,
      {
        'adx' : number,
        'hma' : number,
        'rsi' : number,
        'emaFast' : number,
        'emaSlow' : number,
        'stochasticFast' : number,
        'stochasticSlow' : number,
        'macd' : number,
        'currentCandleFullWickRatio' : number,
        'candleCountCurrentTrend' : bigint,
        'momentum' : number,
        'currentCandleMaxBodyWickRatio' : number,
        'dmiDirectional' : number,
        'currentCandleFullBodyWickRatio' : number,
      },
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      boolean,
      boolean,
      bigint,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      [] | [
        { 'closeInCurrentMinute' : boolean, 'continuationAfterLoss' : boolean }
      ],
      [] | [
        { 'closeInCurrentMinute' : boolean, 'continuationAfterLoss' : boolean }
      ],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];