/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface UserProfile {
    name: string;
    preferredAsset?: Asset;
}
export interface TradeAnalysis {
    id: string;
    secondContinuation?: {
        closeInCurrentMinute: boolean;
        continuationAfterLoss: boolean;
    };
    totalBearishCandles: bigint;
    endingMomentumPercentage: number;
    momentumActivePercentage: number;
    asset: Asset;
    totalHammerCandles: bigint;
    userCorrectedSignal?: Signal;
    generatedSignal: Signal;
    confidenceScoreAfterCorrection: number;
    owner: Principal;
    totalBullishCandles: bigint;
    trapWickActive: boolean;
    trapWicksTriggered: boolean;
    strategy: Strategy;
    highMomentumPercentage: number;
    strongMomentumPattern: boolean;
    finalWickAttempt: boolean;
    failedWickAttempts: bigint;
    trendStartPercentage: number;
    totalBeltCandles: bigint;
    isContinuationTrade: boolean;
    reversalPercentage: number;
    createdTimestamp: Time;
    weakMomentumPercenage: number;
    indicators: {
        adx: number;
        hma: number;
        rsi: number;
        emaFast: number;
        emaSlow: number;
        stochasticFast: number;
        stochasticSlow: number;
        macd: number;
        currentCandleFullWickRatio: number;
        candleCountCurrentTrend: bigint;
        momentum: number;
        currentCandleMaxBodyWickRatio: number;
        dmiDirectional: number;
        currentCandleFullBodyWickRatio: number;
    };
    trapStrongReversalPattern: boolean;
    closedTimestamp?: Time;
    trapDojiCandle: boolean;
    confidence: number;
    firstContinuation?: {
        closeInCurrentMinute: boolean;
        continuationAfterLoss: boolean;
    };
    outcome?: Outcome;
    trapResistanceReversalPercentage: number;
    totalDojiCandles: bigint;
    totalInvertedHammerCandles: bigint;
}
export enum Asset {
    eurUsdOtc = "eurUsdOtc",
    usdJpyOtc = "usdJpyOtc"
}
export enum Outcome {
    win = "win",
    loss = "loss",
    notTaken = "notTaken",
    unknown_ = "unknown"
}
export enum Signal {
    put = "put",
    call = "call",
    noTrade = "noTrade"
}
export enum Strategy {
    colorFollowsColor = "colorFollowsColor",
    combined = "combined",
    trapWicks = "trapWicks"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    analysisIdExists(id: string): Promise<boolean>;
    anyAnalysisAssetIsEurUsdOtc(): Promise<boolean>;
    anyTradeAnalysisCreatedBefore(time: Time): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteTradeAnalysis(id: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getNumAnalyses(): Promise<bigint>;
    getTradeAnalyses(): Promise<Array<TradeAnalysis>>;
    getTradeAnalysesByOutcome(outcomeFilter: Outcome | null): Promise<Array<TradeAnalysis>>;
    getTradeAnalysesSortedByTime(): Promise<Array<TradeAnalysis>>;
    getTradeAnalysis(id: string): Promise<TradeAnalysis>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasAnalysisWithOutcome(outcome: Outcome): Promise<boolean>;
    hasTradeAnalysisWithConfidence(confidence: number): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    storeTradeAnalysis(id: string, asset: Asset, strategy: Strategy, generatedSignal: Signal, confidence: number, createdTimestamp: Time, closedTimestamp: Time | null, outcome: Outcome | null, userCorrectedSignal: Signal | null, confidenceScoreAfterCorrection: number, indicators: {
        adx: number;
        hma: number;
        rsi: number;
        emaFast: number;
        emaSlow: number;
        stochasticFast: number;
        stochasticSlow: number;
        macd: number;
        currentCandleFullWickRatio: number;
        candleCountCurrentTrend: bigint;
        momentum: number;
        currentCandleMaxBodyWickRatio: number;
        dmiDirectional: number;
        currentCandleFullBodyWickRatio: number;
    }, totalBearishCandles: bigint, totalBullishCandles: bigint, totalDojiCandles: bigint, totalHammerCandles: bigint, totalInvertedHammerCandles: bigint, totalBeltCandles: bigint, trapWicksTriggered: boolean, isContinuationTrade: boolean, failedWickAttempts: bigint, trapStrongReversalPattern: boolean, trapDojiCandle: boolean, strongMomentumPattern: boolean, trapWickActive: boolean, finalWickAttempt: boolean, momentumActivePercentage: number, highMomentumPercentage: number, weakMomentumPercenage: number, reversalPercentage: number, endingMomentumPercentage: number, trendStartPercentage: number, trapResistanceReversalPercentage: number, firstContinuation: {
        closeInCurrentMinute: boolean;
        continuationAfterLoss: boolean;
    } | null, secondContinuation: {
        closeInCurrentMinute: boolean;
        continuationAfterLoss: boolean;
    } | null): Promise<void>;
}
import type { Asset as _Asset, Outcome as _Outcome, Signal as _Signal, Strategy as _Strategy, Time as _Time, TradeAnalysis as _TradeAnalysis, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async analysisIdExists(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.analysisIdExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analysisIdExists(arg0);
            return result;
        }
    }
    async anyAnalysisAssetIsEurUsdOtc(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.anyAnalysisAssetIsEurUsdOtc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.anyAnalysisAssetIsEurUsdOtc();
            return result;
        }
    }
    async anyTradeAnalysisCreatedBefore(arg0: Time): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.anyTradeAnalysisCreatedBefore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.anyTradeAnalysisCreatedBefore(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteTradeAnalysis(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTradeAnalysis(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTradeAnalysis(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNumAnalyses(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNumAnalyses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNumAnalyses();
            return result;
        }
    }
    async getTradeAnalyses(): Promise<Array<TradeAnalysis>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeAnalyses();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeAnalyses();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradeAnalysesByOutcome(arg0: Outcome | null): Promise<Array<TradeAnalysis>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeAnalysesByOutcome(to_candid_opt_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeAnalysesByOutcome(to_candid_opt_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradeAnalysesSortedByTime(): Promise<Array<TradeAnalysis>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeAnalysesSortedByTime();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeAnalysesSortedByTime();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradeAnalysis(arg0: string): Promise<TradeAnalysis> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeAnalysis(arg0);
                return from_candid_TradeAnalysis_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeAnalysis(arg0);
            return from_candid_TradeAnalysis_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasAnalysisWithOutcome(arg0: Outcome): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasAnalysisWithOutcome(to_candid_Outcome_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasAnalysisWithOutcome(to_candid_Outcome_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async hasTradeAnalysisWithConfidence(arg0: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasTradeAnalysisWithConfidence(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasTradeAnalysisWithConfidence(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async storeTradeAnalysis(arg0: string, arg1: Asset, arg2: Strategy, arg3: Signal, arg4: number, arg5: Time, arg6: Time | null, arg7: Outcome | null, arg8: Signal | null, arg9: number, arg10: {
        adx: number;
        hma: number;
        rsi: number;
        emaFast: number;
        emaSlow: number;
        stochasticFast: number;
        stochasticSlow: number;
        macd: number;
        currentCandleFullWickRatio: number;
        candleCountCurrentTrend: bigint;
        momentum: number;
        currentCandleMaxBodyWickRatio: number;
        dmiDirectional: number;
        currentCandleFullBodyWickRatio: number;
    }, arg11: bigint, arg12: bigint, arg13: bigint, arg14: bigint, arg15: bigint, arg16: bigint, arg17: boolean, arg18: boolean, arg19: bigint, arg20: boolean, arg21: boolean, arg22: boolean, arg23: boolean, arg24: boolean, arg25: number, arg26: number, arg27: number, arg28: number, arg29: number, arg30: number, arg31: number, arg32: {
        closeInCurrentMinute: boolean;
        continuationAfterLoss: boolean;
    } | null, arg33: {
        closeInCurrentMinute: boolean;
        continuationAfterLoss: boolean;
    } | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeTradeAnalysis(arg0, to_candid_Asset_n29(this._uploadFile, this._downloadFile, arg1), to_candid_Strategy_n31(this._uploadFile, this._downloadFile, arg2), to_candid_Signal_n33(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_opt_n35(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n36(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21, arg22, arg23, arg24, arg25, arg26, arg27, arg28, arg29, arg30, arg31, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg32), to_candid_opt_n37(this._uploadFile, this._downloadFile, arg33));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeTradeAnalysis(arg0, to_candid_Asset_n29(this._uploadFile, this._downloadFile, arg1), to_candid_Strategy_n31(this._uploadFile, this._downloadFile, arg2), to_candid_Signal_n33(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_opt_n35(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n36(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21, arg22, arg23, arg24, arg25, arg26, arg27, arg28, arg29, arg30, arg31, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg32), to_candid_opt_n37(this._uploadFile, this._downloadFile, arg33));
            return result;
        }
    }
}
function from_candid_Asset_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Asset): Asset {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Outcome_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Outcome): Outcome {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Signal_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Signal): Signal {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Strategy_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Strategy): Strategy {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_TradeAnalysis_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeAnalysis): TradeAnalysis {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        closeInCurrentMinute: boolean;
        continuationAfterLoss: boolean;
    }]): {
    closeInCurrentMinute: boolean;
    continuationAfterLoss: boolean;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Signal]): Signal | null {
    return value.length === 0 ? null : from_candid_Signal_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Outcome]): Outcome | null {
    return value.length === 0 ? null : from_candid_Outcome_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Asset]): Asset | null {
    return value.length === 0 ? null : from_candid_Asset_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    secondContinuation: [] | [{
            closeInCurrentMinute: boolean;
            continuationAfterLoss: boolean;
        }];
    totalBearishCandles: bigint;
    endingMomentumPercentage: number;
    momentumActivePercentage: number;
    asset: _Asset;
    totalHammerCandles: bigint;
    userCorrectedSignal: [] | [_Signal];
    generatedSignal: _Signal;
    confidenceScoreAfterCorrection: number;
    owner: Principal;
    totalBullishCandles: bigint;
    trapWickActive: boolean;
    trapWicksTriggered: boolean;
    strategy: _Strategy;
    highMomentumPercentage: number;
    strongMomentumPattern: boolean;
    finalWickAttempt: boolean;
    failedWickAttempts: bigint;
    trendStartPercentage: number;
    totalBeltCandles: bigint;
    isContinuationTrade: boolean;
    reversalPercentage: number;
    createdTimestamp: _Time;
    weakMomentumPercenage: number;
    indicators: {
        adx: number;
        hma: number;
        rsi: number;
        emaFast: number;
        emaSlow: number;
        stochasticFast: number;
        stochasticSlow: number;
        macd: number;
        currentCandleFullWickRatio: number;
        candleCountCurrentTrend: bigint;
        momentum: number;
        currentCandleMaxBodyWickRatio: number;
        dmiDirectional: number;
        currentCandleFullBodyWickRatio: number;
    };
    trapStrongReversalPattern: boolean;
    closedTimestamp: [] | [_Time];
    trapDojiCandle: boolean;
    confidence: number;
    firstContinuation: [] | [{
            closeInCurrentMinute: boolean;
            continuationAfterLoss: boolean;
        }];
    outcome: [] | [_Outcome];
    trapResistanceReversalPercentage: number;
    totalDojiCandles: bigint;
    totalInvertedHammerCandles: bigint;
}): {
    id: string;
    secondContinuation?: {
        closeInCurrentMinute: boolean;
        continuationAfterLoss: boolean;
    };
    totalBearishCandles: bigint;
    endingMomentumPercentage: number;
    momentumActivePercentage: number;
    asset: Asset;
    totalHammerCandles: bigint;
    userCorrectedSignal?: Signal;
    generatedSignal: Signal;
    confidenceScoreAfterCorrection: number;
    owner: Principal;
    totalBullishCandles: bigint;
    trapWickActive: boolean;
    trapWicksTriggered: boolean;
    strategy: Strategy;
    highMomentumPercentage: number;
    strongMomentumPattern: boolean;
    finalWickAttempt: boolean;
    failedWickAttempts: bigint;
    trendStartPercentage: number;
    totalBeltCandles: bigint;
    isContinuationTrade: boolean;
    reversalPercentage: number;
    createdTimestamp: Time;
    weakMomentumPercenage: number;
    indicators: {
        adx: number;
        hma: number;
        rsi: number;
        emaFast: number;
        emaSlow: number;
        stochasticFast: number;
        stochasticSlow: number;
        macd: number;
        currentCandleFullWickRatio: number;
        candleCountCurrentTrend: bigint;
        momentum: number;
        currentCandleMaxBodyWickRatio: number;
        dmiDirectional: number;
        currentCandleFullBodyWickRatio: number;
    };
    trapStrongReversalPattern: boolean;
    closedTimestamp?: Time;
    trapDojiCandle: boolean;
    confidence: number;
    firstContinuation?: {
        closeInCurrentMinute: boolean;
        continuationAfterLoss: boolean;
    };
    outcome?: Outcome;
    trapResistanceReversalPercentage: number;
    totalDojiCandles: bigint;
    totalInvertedHammerCandles: bigint;
} {
    return {
        id: value.id,
        secondContinuation: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.secondContinuation)),
        totalBearishCandles: value.totalBearishCandles,
        endingMomentumPercentage: value.endingMomentumPercentage,
        momentumActivePercentage: value.momentumActivePercentage,
        asset: from_candid_Asset_n7(_uploadFile, _downloadFile, value.asset),
        totalHammerCandles: value.totalHammerCandles,
        userCorrectedSignal: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.userCorrectedSignal)),
        generatedSignal: from_candid_Signal_n16(_uploadFile, _downloadFile, value.generatedSignal),
        confidenceScoreAfterCorrection: value.confidenceScoreAfterCorrection,
        owner: value.owner,
        totalBullishCandles: value.totalBullishCandles,
        trapWickActive: value.trapWickActive,
        trapWicksTriggered: value.trapWicksTriggered,
        strategy: from_candid_Strategy_n18(_uploadFile, _downloadFile, value.strategy),
        highMomentumPercentage: value.highMomentumPercentage,
        strongMomentumPattern: value.strongMomentumPattern,
        finalWickAttempt: value.finalWickAttempt,
        failedWickAttempts: value.failedWickAttempts,
        trendStartPercentage: value.trendStartPercentage,
        totalBeltCandles: value.totalBeltCandles,
        isContinuationTrade: value.isContinuationTrade,
        reversalPercentage: value.reversalPercentage,
        createdTimestamp: value.createdTimestamp,
        weakMomentumPercenage: value.weakMomentumPercenage,
        indicators: value.indicators,
        trapStrongReversalPattern: value.trapStrongReversalPattern,
        closedTimestamp: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.closedTimestamp)),
        trapDojiCandle: value.trapDojiCandle,
        confidence: value.confidence,
        firstContinuation: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.firstContinuation)),
        outcome: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.outcome)),
        trapResistanceReversalPercentage: value.trapResistanceReversalPercentage,
        totalDojiCandles: value.totalDojiCandles,
        totalInvertedHammerCandles: value.totalInvertedHammerCandles
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    preferredAsset: [] | [_Asset];
}): {
    name: string;
    preferredAsset?: Asset;
} {
    return {
        name: value.name,
        preferredAsset: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.preferredAsset))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    put: null;
} | {
    call: null;
} | {
    noTrade: null;
}): Signal {
    return "put" in value ? Signal.put : "call" in value ? Signal.call : "noTrade" in value ? Signal.noTrade : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    colorFollowsColor: null;
} | {
    combined: null;
} | {
    trapWicks: null;
}): Strategy {
    return "colorFollowsColor" in value ? Strategy.colorFollowsColor : "combined" in value ? Strategy.combined : "trapWicks" in value ? Strategy.trapWicks : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    win: null;
} | {
    loss: null;
} | {
    notTaken: null;
} | {
    unknown: null;
}): Outcome {
    return "win" in value ? Outcome.win : "loss" in value ? Outcome.loss : "notTaken" in value ? Outcome.notTaken : "unknown" in value ? Outcome.unknown : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eurUsdOtc: null;
} | {
    usdJpyOtc: null;
}): Asset {
    return "eurUsdOtc" in value ? Asset.eurUsdOtc : "usdJpyOtc" in value ? Asset.usdJpyOtc : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradeAnalysis>): Array<TradeAnalysis> {
    return value.map((x)=>from_candid_TradeAnalysis_n12(_uploadFile, _downloadFile, x));
}
function to_candid_Asset_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Asset): _Asset {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_Outcome_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Outcome): _Outcome {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_Signal_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Signal): _Signal {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_Strategy_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Strategy): _Strategy {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Outcome | null): [] | [_Outcome] {
    return value === null ? candid_none() : candid_some(to_candid_Outcome_n25(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Signal | null): [] | [_Signal] {
    return value === null ? candid_none() : candid_some(to_candid_Signal_n33(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closeInCurrentMinute: boolean;
    continuationAfterLoss: boolean;
} | null): [] | [{
        closeInCurrentMinute: boolean;
        continuationAfterLoss: boolean;
    }] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    preferredAsset?: Asset;
}): {
    name: string;
    preferredAsset: [] | [_Asset];
} {
    return {
        name: value.name,
        preferredAsset: value.preferredAsset ? candid_some(to_candid_Asset_n29(_uploadFile, _downloadFile, value.preferredAsset)) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Outcome): {
    win: null;
} | {
    loss: null;
} | {
    notTaken: null;
} | {
    unknown: null;
} {
    return value == Outcome.win ? {
        win: null
    } : value == Outcome.loss ? {
        loss: null
    } : value == Outcome.notTaken ? {
        notTaken: null
    } : value == Outcome.unknown ? {
        unknown_: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Asset): {
    eurUsdOtc: null;
} | {
    usdJpyOtc: null;
} {
    return value == Asset.eurUsdOtc ? {
        eurUsdOtc: null
    } : value == Asset.usdJpyOtc ? {
        usdJpyOtc: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Strategy): {
    colorFollowsColor: null;
} | {
    combined: null;
} | {
    trapWicks: null;
} {
    return value == Strategy.colorFollowsColor ? {
        colorFollowsColor: null
    } : value == Strategy.combined ? {
        combined: null
    } : value == Strategy.trapWicks ? {
        trapWicks: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Signal): {
    put: null;
} | {
    call: null;
} | {
    noTrade: null;
} {
    return value == Signal.put ? {
        put: null
    } : value == Signal.call ? {
        call: null
    } : value == Signal.noTrade ? {
        noTrade: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
